version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=app
      - DB_PASS=Flora2025! # This is just for development environment
      - DB_NAME=english_dictionary
      - ENVIRONMENT=development
      - JWT_SECRET=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: english_dictionary
      POSTGRES_USER: app
      POSTGRES_PASSWORD: Flora2025! # This is just for development environment
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
